Update customer_account.xml
opengento/magento2-gdpr pull request #83
Opened 2021-02-14 11:32 UTC by mageho

Using block Magento\Customer\Block\Account\SortLinkInterface instead of Magento\Framework\View\Element\Html\Link\Current
to be able to sort link by sortOrder function

2021-02-14 17:04 UTC, thomas-kl1 requested changes

2021-02-14 17:04 UTC, thomas-kl1 commented on view/frontend/layout/customer_account.xml
> +            <block class="Magento\Customer\Block\Account\SortLinkInterface" name="customer-account-navigation-account-privacy-link">
Please keep `ifconfig="gdpr/general/enabled"` so the link can be enabled from the settings.

2021-02-14 17:04 UTC, thomas-kl1 commented on view/frontend/layout/customer_account.xml
> +                    <argument name="label" xsi:type="string" translate="true"><![CDATA[Privacy Settings]]></argument>
Why do we need the CDATA markup here?

2021-02-14 17:05 UTC, thomas-kl1 commented
Hi @mageho ! Thank you a lot for your contribution! You are right we should use sortable element in the account menu.
Could you check my review?

2021-02-15 08:10 UTC, mageho commented
Good morning Thomas,

You are welcome!

Here you go for your review

Ilan

2021-02-15 08:11 UTC, thomas-kl1 approved these changes

2021-02-15 08:11 UTC, merged